# Python ile Veri Analizi : NumPy
 + NumPy matematik ve istatistik denildiğinde akla gelen ilk kütüphanedir.
 + Verimli veri saklama ve vektörel operasyonlardır -diğer anlamıyla yüksek seviye işlemlerdir- 
 + Listelere kıyasla daha hızlı işlem yapma yeteneğine sahiptir.
 + Sabit tipte veri tutar.
 + Döngü yazmadan basit seviye işlemleri gerçekleitirmeyi sağlar.
    + NumPy Özellikleri
    + NumPy Array'i oluşturmak (Creating Numpy Arrays)
    + NumPy Array özellikleri (Attibutes of Numpy Arrays)
    + Yeniden şekillendirme (Reshaping)
    + Index Seçimi (Index selection)
    + Slicing
    + Fancy Index
    + Numpy'da koşullu işlemler (Conditions on Numpy)
    + Matematiksel işlemler (Mathematical Operations)
---
##### NumPy Özellikleri
Numpy kütüphanesini çalışmaya dahil etmek;

In [26]:
import numpy as np

> Hız:
> + Hızlı olmasının sebebi sabit tipte veri tutması.
> + Yüksek seviyeden (vektörel seviyeden) işlemler yapmayı sağlıyor, bu da daha az çabayla daha çok işlemler yapmayı sağlıyor.
---
Amaç: İki listenin çarpımını boş bir listeye aktarmak.

In [3]:
a = [1, 2, 3, 4]

In [4]:
b = [2, 3, 4, 5]

Klasik python yolu;


In [20]:
ab = []

for index in range(0, len(a)):
    ab.append(a[index] * b[index])
    

In [15]:
ab

[2, 6, 12, 20]

NumPy python yolu;

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

a * b

array([ 2,  6, 12, 20])

##### NumPy Array'i oluşturmak (Creating Numpy Arrays)
Numpy kütüphanesini çalışmaya dahil etmek;

In [21]:
import numpy as np

> + Liste üzerinden bir NumPy array oluşturulur.

In [22]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

> + Tipleri sıfırdan oluşan array oluşturma, array'in tipini kedimiz `dtype` yöntemiyle belirleyebiliriz.

In [23]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

> + Belirli bir aralıktan array oluşturma işlemi.
> + Üç adet argüman vardır 
     + Birincisine : Alt sınır, herhangi bir ifade girmezsek sıfır olarak kabul edecektir.
     + İkincisine : Üst sınır
     + Üçüncüsüne : kaç array seçimi yapılacağı bilgisi.  

In [24]:
np.random.randint(0, 10, size=10)

array([5, 9, 3, 3, 8, 2, 3, 6, 3, 7])

> + Belirli bir istatiksel dağılıma göre array üretmek istersek.
> + Üç adet argüman vardır 
     + Birincisine : Normal dağılımın kitlenin ortalamasını 
     + İkincisine : Normal dağılımın standart sapması 
     + Üçüncüsüne : Boyut bilgisi
 

In [25]:
np.random.normal(10, 4, (3,4))

array([[ 2.67447192, 17.08621763, 15.10291205, 10.03247399],
       [ 8.71004487,  4.72134352,  7.30071026,  8.95514971],
       [ 7.78214779, 10.8870376 ,  3.55127556,  6.2381092 ]])

##### NumPy Array özellikleri (Attibutes of Numpy Arrays)
Numpy kütüphanesini çalışmaya dahil etmek;

In [27]:
import numpy as np

Sıfırdan bir array oluşturalım

In [28]:
a = np.random.randint(10, size=5)

In [29]:
a

array([7, 6, 9, 2, 3])

> + ndim: Boyut sayısı

In [30]:
a.ndim

1

> + shape: Boyut bilgisi
> + ikiden fazla boyut bilgisi olsaydı virgülsen sonra her bir boyutun sayı bilgisi gelecekti.

In [31]:
a.shape

(5,)

> + size: Toplam eleman sayısı

In [32]:
a.size

5

> + dtype: array veri tipi

In [33]:
a.dtype

dtype('int32')

##### Yeniden şekillendirme (Reshaping)
+ Elimizdeki bir NumPy array'inin buyutunu değiştirmek istediğimizde -reshaping- metodunu kullanırız.
---
Numpy kütüphanesini çalışmaya dahil etmek;

---
Sıfırdan array oluşturalım;

In [ ]:
import numpy as np

In [34]:
np.random.randint(1, 10, size=9)

array([2, 2, 2, 8, 1, 5, 6, 2, 2])

> Amaç: Elimizdeki array'i iki noyutlu bir array' çevirmek
> + 'reshape' methodunu kullanarak istediğimiz boyut bilgisini giriyoruz.

In [35]:
np.random.randint(1, 10, size=9).reshape(3, 3)

array([[8, 5, 2],
       [6, 4, 9],
       [5, 1, 4]])

> + İşlemi atama üzerinden de gerçekleitirebilirdik.

In [36]:
ar = np.random.randint(1, 10, size=9)

In [38]:
ar.reshape(3, 3)

array([[1, 4, 1],
       [4, 2, 3],
       [1, 2, 1]])

> + !! eleman sayısını göz önünde bulundurarak boyut bilgisini kullanambiliriz.
> + Eleman sayısını `size=10` değiştirirsek boyut değiştirirken `reshape(3, 3)` hata alırız.

In [39]:
np.random.randint(1, 10, size=10).reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

##### Index Seçimi (Index selection)
Numpy kütüphanesini çalışmaya dahil etmek;

---
Sıfırdan array oluşturalım;

In [41]:
import numpy as np

In [43]:
a = np.random.randint(10, size=10)

In [45]:
a

array([4, 4, 0, 0, 2, 6, 7, 0, 4, 7])

> + İndex seçimi

In [46]:
a[2]

0

> + Dilimleme işlemiyle index seçimi

In [47]:
a[0:4]

array([4, 4, 0, 0])

> + İstediğimiz index'i değiştirmek 

In [48]:
a[0] = 999

In [49]:
a

array([999,   4,   0,   0,   2,   6,   7,   0,   4,   7])

> İki boyutlu array için seçim işlemi 
> + İki Boyutlu bir array tanımlayalım

In [52]:
m = np.random.randint(10, size=(3,5))

In [53]:
m

array([[6, 3, 4, 7, 5],
       [8, 5, 8, 0, 1],
       [9, 5, 6, 4, 0]])

> + iki argüman girilir
    + Birinci : satır biligisini temsil eder
    + İkinci : Sütun bilgisi temsil eder

In [55]:
m[0, 2]

4

> + İki boyutlu array için eleman değitirme işlemi

In [58]:
m[2, 3] = 999

In [59]:
m

array([[  6,   3,   4,   7,   5],
       [  8,   5,   8,   0,   1],
       [  9,   5,   6, 999,   0]])

> + NamPy sabit tipli bir array olduğu için flooat değerlerini int gibi alır;

In [60]:
m[2,1] = 2.11

In [61]:
m

array([[  6,   3,   4,   7,   5],
       [  8,   5,   8,   0,   1],
       [  9,   2,   6, 999,   0]])

> + İki boyutlu array'lerde dilimleme işlemi 

+ Tüm satıları seç, 0 sütunu seç

In [64]:
m[:, 0]

array([6, 8, 9])

+ Birinci satır, tüm sütun

In [66]:
m[1, :]

array([8, 5, 8, 0, 1])

+ Hem satırlardan hem de sütunlardan belli bir aralık .

In [71]:
m[0:2, 1:3]

array([[3, 4],
       [5, 8]])

##### Fancy Index
> Bir array ya da DataFrame içine oluşturduğumuz index bilgilerinin bulunduğu liste konularak array şeklinde oluşturduğumuz listedeki index'lerin seçilmesidir.

---
> + Belirli bir erek oluştumak için adım sayısını verilen array
+ `np.arange(0, 30, 3)` 
    + Birinci : Alt sınır
    + İkinci : Üst sınır
    + Üçüncü : Adım sayısı
---
Numpy kütüphanesini çalışmaya dahil etmek;

---
Sıfırdan array oluşturalım;

In [1]:
import numpy as np

> 0'dan 30'a kadar 3'er 3'er artacak bir array tanımlayalım.

In [2]:
v = np.arange(0, 30, 3)

In [4]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

> 'catch' adında oluşturduğumuz liste index listesidir.

In [5]:
catch = [1, 2, 3]

> Oluşturduğumuz array yapısının içerisine index listesini yerleştirdiğimizde index'lere karşılık gelen değerler ekrana çıktı şeklinde bastırılır.

In [6]:
v[catch]

array([3, 6, 9])

##### Numpy'da koşullu işlemler (Conditions on Numpy)
Numpy kütüphanesini çalışmaya dahil etmek;

---
Sıfırdan array oluşturalım;

In [7]:
import numpy as np

In [8]:
v = np.array([1, 2, 3, 4, 5])

In [9]:
v

array([1, 2, 3, 4, 5])

> + NumPy' herhangi bir ifadenin sorgusunu yaptığımızda hızlı bir şekilde işlme gerçekleşir 
> + `v < 3` v listesinin içerinindeki tüm elemanlarının sorgusu True ve False şeklinde ekrana çıktı veriri

In [10]:
v < 3

array([ True,  True, False, False, False])

> + Yukarıdaki ifadeyi array'in içerisinden seç işlemine alırsak True olarak gördüklerini seçecek False olarak gördüklerini seçmeyecektir.

In [11]:
v[v < 3]

array([1, 2])

In [12]:
v[v != 3]

array([1, 2, 4, 5])

In [15]:
v[v >= 3]

array([3, 4, 5])

##### Matematiksel işlemler (Mathematical Operations)
---
Numpy kütüphanesini çalışmaya dahil etmek;

---
Sıfırdan array oluşturalım;

In [16]:
import numpy as np

In [17]:
v = np.array([1, 2, 3, 4, 5])

> Operatörler aracılığyla matematiksel işlemler;

In [18]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [21]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [22]:
v ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [23]:
v - 3

array([-2, -1,  0,  1,  2])

> Metodlar yardımıylada matematiksel işlemler;

> + Çıkarma işlemi için;       

In [24]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

> + Toplama işlemi için;

In [25]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

> + Ortalama işlemi için;


In [26]:
np.mean(v)

3.0

> + Toplam alma işlemi için;

In [29]:
np.sum(v)

15

> + Minumum değeri için;

In [30]:
np.min(v)

1

> + Mkximum değeri için;

In [31]:
np.max(v)

5

> + Varyans işlemi için;

In [32]:
np.var(v)

2.0

##### NumPy ile iki bilinmeyenli denklem çözümü
+ 5*x0 + x1 = 12
+ x0 + 3*x1 = 10
> Katsayılarını belirli bir yapıda gönderirsek işlemi yapmış oluruz.
> + a array'indeki ilk elemanlar : birinci değişkenin katsayıları 
ikinci elemanlar : ikinci değişkenin katsayıları.
> + b array'indeki değişkenler ise denklemin sonuçlarıdır.

In [33]:
a = np.array([[5, 1], [1, 3]])

In [34]:
b = np.array([12, 10])

In [35]:
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])